hostname: k3s-master
ssh_authorized_keys:
  - github:gumbagubanga

k3os:
  dns_nameservers:
    - 1.1.1.1
    - 8.8.8.8
  ntp_servers:
    - 0.de.pool.ntp.org
    - 1.de.pool.ntp.org

  token: A_RANDOM_TOKEN_YOU_LIKE
